export const cryptoData = [
	{ id: 1, name: 'Bitcoin', label: 'BTC', image: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png' },
	{ id: 2, name: 'Ethereum', label: 'ETH', image: 'https://cryptologos.cc/logos/ethereum-eth-logo.png' },
	{ id: 3, name: 'Litecoin', label: 'LTC', image: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png' },
	{ id: 5, name: 'Cardano', label: 'ADA', image: 'https://cryptologos.cc/logos/cardano-ada-logo.png' },
	{ id: 6, name: 'Polkadot', label: 'DOT', image: 'https://cryptologos.cc/logos/polkadot-dot-logo.png' },
	{ id: 7, name: 'Binance Coin', label: 'BNB', image: 'https://cryptologos.cc/logos/binance-coin-bnb-logo.png' },
	{ id: 8, name: 'Solana', label: 'SOL', image: 'https://cryptologos.cc/logos/solana-sol-logo.png' },
	{ id: 9, name: 'Dogecoin', label: 'DOGE', image: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png' },
	{ id: 10, name: 'Chainlink', label: 'LINK', image: 'https://cryptologos.cc/logos/chainlink-link-logo.png' },
	{ id: 11, name: 'Polygon', label: 'MATIC', image: 'https://cryptologos.cc/logos/polygon-matic-logo.png' },
	{ id: 12, name: 'Uniswap', label: 'UNI', image: 'https://cryptologos.cc/logos/uniswap-uni-logo.png' },
	{ id: 13, name: 'Avalanche', label: 'AVAX', image: 'https://cryptologos.cc/logos/avalanche-avax-logo.png' },
	{ id: 14, name: 'Shiba Inu', label: 'SHIB', image: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png' },
	{ id: 15, name: 'Terra', label: 'LUNA', image: 'https://cryptologos.cc/logos/terra-luna-logo.png' },
	{ id: 16, name: 'VeChain', label: 'VET', image: 'https://cryptologos.cc/logos/vechain-vet-logo.png' },
	{ id: 17, name: 'Stellar', label: 'XLM', image: 'https://cryptologos.cc/logos/stellar-xlm-logo.png' },
	{ id: 18, name: 'Cosmos', label: 'ATOM', image: 'https://cryptologos.cc/logos/cosmos-atom-logo.png' },
	{ id: 19, name: 'Tezos', label: 'XTZ', image: 'https://cryptologos.cc/logos/tezos-xtz-logo.png' },
	{ id: 20, name: 'Filecoin', label: 'FIL', image: 'https://cryptologos.cc/logos/filecoin-fil-logo.png' },
];
